run_name: AL_Test
data:
  dataset: AMC
  mode: train
  batch_size: 3
  batch_size_val: 8
training:
  num_epochs: 2
model:
  name: ternaus_net
  network_params:
    pretrained: True
resume:
  resume_from: 'SAVED MODEL'
  saved_model: 'best_model_13.pth'
  saved_optimizer:
active_learn:
  method: least_confident
  init_pool_size: 5
  budget: 5
  acquisition_steps: 5
