run_name: AL_UNet_Testing
data:
  dataset: AMC
  mode: train
  batch_size: 8
  batch_size_val: 10
training:
  num_epochs: 1
  use_ensemble: True
  ensemble:
    number_models: 3
model:
  name: unet
  network_params:
    num_filters: 32
    dropout: False
    dropout_p: 0.25
active_learn:
  method: weighted_max_entropy_ensemble
  init_pool_size: 2
  init_scans: ['1239608', '324780001']
  budget: 1
  acquisition_steps: 11
  mc_passes: 5
  weights_type: minmax