run_name: AL_Ternaus_LC_MC_Again
data:
  dataset: AMC
  mode: train
  batch_size: 4
  batch_size_val: 8
training:
  num_epochs: 500
model:
  name: ternaus_net
#resume:
#  resume_from: 'SAVED MODEL'
#  saved_model: 'ternaus_dropout.pth'
#  saved_optimizer:
active_learn:
  method: least_confident_mc
  init_pool_size: 100
  budget: 50
  acquisition_steps: 15
  mc_passes: 50