run_name: Default
data:
  dataset: AMC
  mode: train
  batch_size: 8
  batch_size_val: 10
  num_workers: 4
  run_val_on_train: False
training:
  bayesian: False
  beta_type: Blundell
  seed:
  num_epochs: 75
  optimizer:
    name: adam
    lr: 0.001
    weight_decay: 0.001
    amsgrad: False
    scheduler: step
    scheduler_params:
      step_size: 30
      gamma: 0.1
#      mode: min
#      patience: 10
#      factor: 0.5
  loss_fn:
    name: bce_and_jaccard
  early_stop_fn: f1_score
  early_stop: True
  patience: 31
  use_ensemble: False
  ensemble:
    number_models: 3
model:
  name: unet
  network_params:
    num_filters: 32
#    pretrained: True
    dropout: False
    dropout_p: 0.25
resume:
  resume_from:
  saved_model:
  saved_optimizer:
binarize_threshold: 0.5
al_mode: False
prediction:
  mode: single
  mc_passes: 25
active_learn:
  weighted: False