run_name: Default
data:
  dataset: AMC
  mode: train
  batch_size: 10
  batch_size_val: 16
  num_workers: 4
  run_val_on_train: False
training:
  type: standard
#  beta_type: Blundell
  seed:
  num_epochs: 75
  optimizer:
    name: adam
    lr: 0.001
    weight_decay: 0.0005
    amsgrad: False
    scheduler: step
    scheduler_params:
      step_size: 30
      gamma: 0.1
#      mode: min
#      patience: 10
#      factor: 0.5
  loss_fn:
    name: bce_and_jaccard
    ignore_index: 255   # CITYSCAPES
    ###
    mse_factor: 0.5
    mse_warmup: True
    mse_factor_type: gradual
    mse_step_interval: 15
    mse_step_size: 0.1
    ###
    kld_factor: 2
    kld_warmup: False
    kld_step_interval: 15
    kld_step_size: 0.1
    ###
  early_stop_fn: f1_score
  early_stop: False
  patience: 31
  use_ensemble: False
  ensemble:
    number_models: 3
model:
  name: unet
  network_params:
    num_filters: 32
#    pretrained: True
    dropout: False
    dropout_p: 0.25
    ###
    latent_dim: 32
    load_standard_unet: False
resume:
  resume_from:
  saved_model:
  saved_optimizer:
binarize_threshold: 0.5
al_mode: False
prediction:
  mode: single
  mc_passes: 25
active_learn:
  weighted: False