run_name: BayesUnet_Test
data:
  dataset: AMC
  mode: train
  batch_size: 4
  batch_size_val: 8
  num_workers: 4
  run_val_on_train: False
training:
  bayesian: True
  beta_type: Blundell
  seed:
  num_epochs: 500
  optimizer:
    name: adam
    lr: 0.001
    weight_decay: 0.001
    amsgrad: False
    scheduler: plateau
    scheduler_params:
      step_size: 30
      gamma: 0.5
      mode: min
      patience: 10
      factor: 0.5
  loss_fn:
    name: bce_and_jaccard
  early_stop_fn: f1_score
  patience: 20
  use_ensemble: False
  ensemble:
    number_models: 3
model:
  name: bbb_unet
  network_params:
    num_filters: 32
    pretrained: True
    dropout: True
resume:
  resume_from:
  saved_model:
  saved_optimizer:
binarize_threshold: 0.5
al_mode: False
prediction:
  mode: single
  mc_passes: 10