run_name: Ensemble_UNet
data:
  dataset: AMC
  mode: train
  batch_size: 4
  batch_size_val: 8
  num_workers: 4
  run_val_on_train: False
training:
  seed:
  num_epochs: 75
  optimizer:
    name: adam
    lr: 0.001
    weight_decay: 0.001
    amsgrad: True
    scheduler: step
    lr_cycle: 30
  loss_fn:
    name: bce_and_jaccard
  patience: 15
  early_stop_fn: iou_score
  use_ensemble: True
  ensemble:
    number_models: 5
model:
  name: unet_v2
  network_params:
    num_filters: 32
    pretrained: True
    dropout: False
resume:
  resume_from:
  saved_model:
  saved_optimizer:
binarize_threshold: 0.5
al_mode: False
prediction:
  mode: single
  mc_passes: 10