run_name: FCN8_Dummy
data:
  dataset: AMC Dummy
  mode: train
  batch_size: 4
  batch_size_val: 8
  num_workers: 4
  run_val_on_train: False
training:
  seed:
  num_epochs: 50
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.0001
    amsgrad: True
    scheduler: step
    lr_cycle: 20
  loss_fn:
    name: bce_and_jaccard
  log_interval: 20
  save_model_interval: 50
  ignite_history_size: 1
model:
  name: fcn8
  network_params:
    learn_upconv: True
    use_pretrained: False
resume:
  resume_from:
  saved_model:
  saved_optimizer: