run_name: Ternaus
data:
  dataset: AMC New
  mode: train
  batch_size: 4
  batch_size_val: 8
  num_workers: 4
  run_val_on_train: False
training:
  seed:
  num_epochs: 75
  optimizer:
    name: adam
    lr: 0.001
    weight_decay: 0.0001
    amsgrad: True
    scheduler: step
    lr_cycle: 20
  loss_fn:
    name: bce_and_jaccard
  log_interval: 20
  save_model_interval: 50
  ignite_history_size: 1
model:
  name: ternaus_net
  network_params:
    pretrained: True
resume:
  resume_from:
  saved_model:
  saved_optimizer: