run_name:
data:
  dataset: AMC
  train_split: train
  val_split: val
  batch_size: 1
  num_workers: 0
training:
  seed:
  num_epochs: 50
  lr: 0.001
  weight_decay: 0
  amsgrad: False
  scheduler: step
  lr_cycle: 20
  log_interval: 20
  save_model_interval: 10
  ignite_history_size: 5
  loss_fn:
    name: bce_loss_2d
model:
  name: unet
  resume_from:
  saved_model: 'final_model_1'
  saved_optimizer: 'final_optimizer_1'
  network_params:
    batch_norm: False
    up_conv: True