data:
  dataset: AMC
  train_split: train
  val_split: val
  batch_size: 4
  num_workers: 0
training:
  num_epochs: 100
  lr: 0.01
  weight_decay: 0
  amsgrad: False
  log_interval: 20
  save_model_interval: 5
  ignite_history_size: 5
  loss_fn:
    name: bce_loss_2d
  scheduler: step
  lr_cycle: 25
model:
  name: unet
  pretrained_network: None
  network_params: {}