data:
  dataset: AMC
  train_split: train
  val_split: val
  batch_size: 32
  num_workers: 0
training:
  num_epochs: 10
  lr: 0.001
  log_interval: 5
  save_model_interval: 5
  ignite_history_size: 5
model:
  name: ffnn
  pretrained_network: None
  network_params: {}